/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f3',
        'surface-container': '#efeded',
        'surface-container-high': '#e9e8e7',
        'surface-container-highest': '#e4e2e2',
        'surface-variant': '#e4e2e2',
        'surface-dim': '#dbdad9',
        'surface-bright': '#fbf9f8',
        surface: '#fbf9f8',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#603e39',
        'inverse-surface': '#303031',
        'inverse-on-surface': '#f2f0f0',
        primary: '#bc0100',
        'primary-container': '#eb0000',
        'primary-fixed': '#ffdad4',
        'primary-fixed-dim': '#ffb4a8',
        'on-primary': '#ffffff',
        'on-primary-container': '#fffbff',
        'on-primary-fixed': '#410000',
        'on-primary-fixed-variant': '#930100',
        'inverse-primary': '#ffb4a8',
        secondary: '#5f5e5e',
        'secondary-container': '#e5e2e1',
        'secondary-fixed': '#e5e2e1',
        'secondary-fixed-dim': '#c8c6c5',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#656464',
        'on-secondary-fixed': '#1c1b1b',
        'on-secondary-fixed-variant': '#474646',
        tertiary: '#5b5c5c',
        'tertiary-container': '#737575',
        'tertiary-fixed': '#e2e2e2',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fcfcfc',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#454747',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        outline: '#956d67',
        'outline-variant': '#ebbbb4',
        background: '#fbf9f8',
        'on-background': '#1b1c1c',
        'surface-tint': '#c00100',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        gutter: '16px',
        margin: '24px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'title-sm': ['16px', { lineHeight: '22px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
